# Generated by Django 3.2.15 on 2022-09-14 19:45

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=200)),
                ('system', models.CharField(choices=[('3.5e', 'D&D 3.5e'), ('PF', 'Pathfinder'), ('4e', 'D&D 4e'), ('5e', 'D&D 5e'), ('6e', 'D&D 6e Playtest')], max_length=200)),
                ('can_dm', models.BooleanField(default=False)),
                ('travel_range', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('gis_point', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point([]), null=True, srid=4326)),
                ('available_dms', models.ManyToManyField(blank=True, default=None, to='core.GameRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'system')},
            },
        ),
    ]
