# Generated by Django 3.2.15 on 2022-09-04 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequest',
            old_name='Name',
            new_name='RequestName',
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='System',
            field=models.CharField(choices=[('3.5e', 'D&D 3.5e'), ('PF', 'Pathfinder'), ('4e', 'D&D 4e'), ('5e', 'D&D 5e'), ('6e', 'D&D 6e Playtest')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='gamerequest',
            unique_together={('UserID', 'System')},
        ),
    ]
