# Generated by Django 3.2.15 on 2022-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220904_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='CanDM',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='TravelRange',
            field=models.IntegerField(default=False),
        ),
    ]
