# Generated by Django 3.2.15 on 2022-09-04 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220904_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerequest',
            name='GISPoint',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
