# Generated by Django 3.2.15 on 2022-09-04 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gamerequest_gispoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerequest',
            name='GISPoint',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326),
        ),
    ]
