# Generated by Django 3.2.15 on 2022-09-11 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20220905_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequest',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='CanDM',
            new_name='can_dm',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='GISPoint',
            new_name='gis_point',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='RequestName',
            new_name='request_name',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='System',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='TravelRange',
            new_name='travel_range',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='UserID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='gamerequest',
            old_name='ZIP',
            new_name='zip',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='available_dms',
            field=models.ManyToManyField(blank=True, related_name='_core_gamerequest_available_dms_+', to='core.GameRequest'),
        ),
        migrations.AlterUniqueTogether(
            name='gamerequest',
            unique_together={('user_id', 'system')},
        ),
    ]
