# Generated by Django 3.2.15 on 2022-09-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gamerequest_available_dms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
